
export const FETCH_STATE = 'FETCH_STATE'
export const SET_ENTRIES = 'SET_ENTRIES'
export const NEXT = 'NEXT'
export const VOTE = 'VOTE'
export const START_VOTING = 'START_VOTING'
export const STOP_VOTING = 'STOP_VOTING'
export const ADD_VOTING = 'ADD_VOTING'
export const CHANGE_VOTING = 'CHANGE_VOTING'
export const REMOVE_VOTING = 'REMOVE_VOTING'
